services:
  backend:
    image: python:3.9-slim
    container_name: flask-backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    image: nginx:alpine
    container_name: nginx-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
